spring:
  profiles:
    active: git
---
spring:
  profiles: native
  cloud:
    config:
      server:
        native:
          search-locations: 'file://PATH_TO_MICROSERVICES_PROJECT/ms-config-properties/{application}/{profile}'
---
spring:
  profiles: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/isilona/microservices/
          search-paths:
            - "ms-config-properties/{application}/{profile}"
