spring:
  profiles:
    active: native
---
spring:
  profiles: native
  cloud:
    config:
      server:
        native:
          search-locations: 'file:///home/jether/Desktop/DEV/workspace/microservice-eureka-kafka/ms-config-properties/{application}/{profile}'
---
spring:
  profiles: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/isilona/microservices/
          search-paths:
            - "ms-config-properties/{application}/{profile}"
